### ISSUE TITLE
df in .homogenize() function is not defined inside the function

### ISSUE THREAD

**Issue by dcolam** [ETHZ-INS/enrichMiR#24]
Error at .homogenizeDEA(x) at enrichMiR.R#75

if (length(abf) == 1) {
    x$meanExpr <- df[, abf]
    if (abf == "baseMean") 
      x$meanExpr <- log(x$meanExpr + 1)

if you df in your environment, it will throw an error.

**Comment by plger** [comment]
sorry for the delay, would be great if you can eventually confirm that it fixes your problem
